drop table customer_customizations;
drop table customer_order_details;
drop table customer_orders;
drop table employee;
drop table supplier_order_details;
drop table supplier_orders;
drop table menu_item_ingredients;
drop table menu_items;
drop table ingredients;